AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation Template to deploy an EC2 instance with a Hello World webpage.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello World" > /var/www/html/index.html

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

Outputs:
  InstancePublicIp:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - MyEC2Instance
      - PublicIp
    Export:
      Name: InstancePublicIp